server:
  port: 8083

spring:
  application:
    name: nova-mail-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 
      register-with-eureka: true
      fetch-registry: true    
  instance:
    hostname: localhost
