server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: DATA-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/dataservice/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
